// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "Rcpp.h"
#include <R_ext/Rdynload.h>
#include "internal.h"
using namespace Rcpp;
 // bayesR
 void bayesR(Rcpp::RObject rOptions);
extern "C"
{
 RcppExport SEXP _AMIGO_bayesR(SEXP rOptionsSEXP) {
 BEGIN_RCPP
     Rcpp::RNGScope rcpp_rngScope_gen;
     Rcpp::traits::input_parameter< Rcpp::RObject >::type rOptions(rOptionsSEXP);
     bayesR(rOptions);
     return R_NilValue;
 END_RCPP
 }

 static const R_CallMethodDef CallEntries[] = {
     {"_AMIGO_bayesR", (DL_FUNC) &_AMIGO_bayesR, 1},
     {NULL, NULL, 0}
 };

 RcppExport void R_init_AMIGO(DllInfo *dll) {
     init_Rcpp_cache();
     R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
     //R_useDynamicSymbols(dll, FALSE);
 }
}
